// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('mytest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('umslogin', async function() {
    await driver.get("https://ums.lpu.in/lpuums/LoginNew.aspx")
    await driver.manage().window().setRect({ width: 1576, height: 625 })
    await driver.findElement(By.id("txtU")).click()
    await driver.findElement(By.id("txtU")).sendKeys("12103196")
    await driver.findElement(By.id("TxtpwdAutoId_8767")).sendKeys("Meena@9549")
    await driver.findElement(By.id("TxtpwdAutoId_8767")).sendKeys(Key.ENTER)
  })
})
